### ISSUE TITLE
How to suggest additions?

### ISSUE THREAD

**Issue by jdonnerstag** [vlang/awesome-v#112]
I've developed the following native V-lang libs. Feel free to add them to your list

- A yaml parser: https://github.com/jdonnerstag/vlang-yaml
- A Rosie RPL parser: https://github.com/jdonnerstag/vlang-rosie

They are both not battle tested, but have a reasonable amount of test cases.

**Comment by serkonda7** [comment]
Just submit an PR where you add them in the corresponding categories.
