### ISSUE TITLE
Add pdf library

### ISSUE THREAD

**Issue by StefanSchroeder** [vlang/awesome-v#124]
This is a simple PDF library. 

https://github.com/vlang/pdf

Could be put in Text or Graphics.
Or get its own section.

**Comment by vkvbit** [comment]
@StefanSchroeder I think it should be in Editor subsection after all its a pdf creation and editing module. I have created a pull request to it. Let's wait for maintainer to merge the PR.

**Comment by ArtemkaKun** [comment]
Already on list
