### ISSUE TITLE
"Isaiah's UI" missing in the list

### ISSUE THREAD

**Issue by ffred** [vlang/awesome-v#192]
"Isaiah's UI" should be there in the "user interface toolkit" section :
https://github.com/isaiahpatton/ui

and probably also the tools he develop with his UI toolkit, in corresponding sections..

**Comment by Delta456** [comment]
Feel free to make a PR for it

**Comment by ffred** [comment]
not near my computer for a few days. will see that later....

**Comment by tobealive** [comment]
I was about to submit a description change, so I could add it in one breath.

Wanted to to submit it as PR and get your review @Delta456 but had selected the wrong origin and my fingers hit the shortcut for push a bit too quick. I hope the change follows all guidelines.

**Comment by Delta456** [comment]
> I was about to submit a description change, so I could add it in one breath.
> 
> Wanted to to submit it as PR and get your review @Delta456 but had selected the wrong origin and my fingers hit the shortcut for push a bit too quick. I hope the change follows all guidelines.

No worries

**Comment by ffred** [comment]
Sorry, had to work on something really different thiss week and didn't got time to do it...
Thanks for doing it.
